cidetor/cidetor/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^', include('words.urls')),
]

cidetor/words/urls.py
from django.conf.urls import url
from . import views

app_name = 'words'

urlpatterns = [
    url(r'^words/load_words$', views.LoadWordsFromCideView.as_view(), name='load_words'),
    url(r'^words/search$', views.SearchView.as_view(), name='search'),

]

cidetor/words/models.py
from mongoengine import Document, StringField
import xml.etree.ElementTree as ET

class Word(Document):
    key = StringField(max_length=255)
    letter = StringField(max_length=2)
    xml = StringField()

    def serialize_xml(self):
        serial = {}
        entry = ET.fromstring(self.xml)
        serial['key'] = entry.get('key')
        definition = entry.find('def')
        if definition is not None:
            serial['definition'] = ET.tostring(definition).decode(encoding='UTF-8')
        
        return serial

cidetor/words/views.py
from django.shortcuts import render
from django.views import View
from words import xml_to_db
from .models import Word


class LoadWordsFromCideView(View):

    def get(self, request):
        return render(request, 'load_words.html') 
    
    def post(self, request):
        xml_to_db.upload_xml_to_db()
        return render(request, 'load_words.html',
                              {'message': "Words have been loaded"})


class SearchView(View):
    def get(self, request):
        return render(request, 'search.html') 
    
    def post(self, request):
        search = request.POST['search']
        try:
            words = Word.objects(key__istartswith=search)
            serials = []
            for word in words:
                serials.append(word.serialize_xml())

            return render(request, 'search.html',
                              {'words': serials,
                              'search':search})
        except Exception as e:
            return render(request, {'error_message':e} )

cidetor/words/templates/load_words.html
<div>
<form action="{% url 'words:load_words' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Submit" />
</form>
</div>
<div>

{% if message %}
    <p><strong>{{message}}</strong></p>
{% endif %}
</div>

cidetor/words/templates/search.html
<div>
<form action="{% url 'words:search' %}" method="post">
    {% csrf_token %}
    <input type="text" name="search" value="{{search}}">
    <br/>
    <input type="submit" value="Submit" />
</form>
</div>

<div>
{% if not words %}
    <p>Word does not exist</p>
{% endif %}
{% for word in words %}
    <p>{{word.key}}: {{word.definition}}</p>
{% endfor %}
</div>